apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- infra-deployments-pr-creator.yaml
- registry-redhat-io-pull-secret.yaml
- quay-push-secret.yaml
namespace: rhtap-build-tenant
