# Needed for build-service pipelines to push to quay.io/redhat-appstudio/build-service
# Temporary, needed until build-service is onboarded to Konflux
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: quay-push-secret
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
spec:
  dataFrom:
    - extract:
        key: production/build/tekton-ci/quay-push-secret
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: appsre-stonesoup-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: quay-push-secret
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .config }}"
